apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: car-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: "git@gitlab.com:orondevops1/gitops-config.git"
    path: infra/car-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
