apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: elasticsearch
      targetRevision: 17.9.29
      helm:
        valueFiles:
          - $values/infra/apps/logging/es-values.yaml
    - repoURL: "git@gitlab.com:orondevops1/gitops-config.git"
      targetRevision: HEAD
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
