apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 59.0.0
    helm:
      values: |
        crds:
          enabled: true

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - host: oron-carapp.ddns.net
              paths:
                - path: /
                  pathType: Prefix

        grafana:
          enabled: true
          persistence:
            enabled: true
            type: sts
            storageClassName: "gp2"
            accessModes:
              - ReadWriteOnce
            size: 20Gi
            finalizers:
              - kubernetes.io/pvc-protection

  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
