apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 2.5.0
    chart: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: car-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
