server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    hosts:
      - argocd.example.com
    paths: ["/"]
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

configs:
  params:
    server.insecure: "true"
  secret:
    argocdServerAdminPassword: $2a$10$bA90iY9oQSCXzQ8nuGodYerzBYE2nIoapMzf/PenfxLUf0AhcW.bq
