logLevel: info
config:
    service: |
        [SERVICE]
            Daemon Off
            Flush 5
            Log_Level debug
            Parsers_File /fluent-bit/etc/parsers.conf
            Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020
            Health_Check On
            Trace_Error On

    inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*car*.log
            Tag kube.*
            Parser docker
            Mem_Buf_Limit 50MB
            Skip_Long_Lines On

    outputs: |
        [OUTPUT]
            Name es
            Match *car*
            Host elasticsearch.efk.svc.cluster.local
            Port 9200
            Index fluent-bit-car-app
            Type _doc
            Logstash_Format On
            Logstash_Prefix car-app
            Retry_Limit False
            Suppress_Type_Name On

    customParsers: |
        [PARSER]
            Name nginx_parser
            Format regex
            Regex ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<request>[^"]*)" (?<status>[^ ]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)"
            Time_Key time_local
            Time_Format %d/%b/%Y:%H:%M:%S %z
