logLevel: info
# luaScripts:
#   setIndex.lua: |
#     function set_index(tag, timestamp, record)
#         index = "dakar-"
#         if record["kubernetes"] ~= nil then
#             if record["kubernetes"]["namespace_name"] ~= nil then
#                 if record["kubernetes"]["container_name"] ~= nil then
#                     record["es_index"] = index
#                         .. record["kubernetes"]["namespace_name"]
#                         .. "-"
#                         .. record["kubernetes"]["container_name"]
#                     return 1, timestamp, record
#                 end
#                 record["es_index"] = index
#                     .. record["kubernetes"]["namespace_name"]
#                 return 1, timestamp, record
#             end
#         end
#         return 1, timestamp, record
#     end
## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
    service: |
        [SERVICE]
            Daemon Off
            Flush 5
            Log_Level debug
            Parsers_File /fluent-bit/etc/parsers.conf
            Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port 2020
            Health_Check On
            Trace_Error On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser docker, cri
            Tag kube.*
            Mem_Buf_Limit 100MB
            Skip_Long_Lines On

        [INPUT]
            Name systemd
            Tag host.*
            Systemd_Filter _SYSTEMD_UNIT=kubelet.service
            Read_From_Tail On

        [INPUT]
            Name tail
            Path /var/log/containers/*ingress-nginx-controller*.log
            Parser nginx_parser
            Tag nginx.*


        [INPUT]
            Name tail
            Path /var/log/containers/*car*.log
            Tag kube.*
            Parser docker
            Mem_Buf_Limit 50MB
            Skip_Long_Lines On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            Buffer_Size False
            K8S-Logging.Parser On
            K8S-Logging.Exclude On

        [FILTER]
            Name parser
            Match nginx.*
            Key_Name log
            Parser nginx_parser
            Preserve_Key On
            Reserve_Data On

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Index fluent-bit
            Type  _doc
            Host elasticsearch.efk.svc.cluster.local
            Port 9200
            tls.verify Off
            Logstash_Format On
            Logstash_Prefix logstash
            Retry_Limit False
            Suppress_Type_Name On

        [OUTPUT]
            Name es
            Match host.*
            Index fluent-bit
            Type  _doc
            Host elasticsearch.efk.svc.cluster.local
            Port 9200
            tls.verify Off
            Logstash_Format On
            Logstash_Prefix node
            Retry_Limit False
            Suppress_Type_Name On

        [OUTPUT]
            Name es
            Match nginx.*
            Index fluent-bit-nginx
            Type  _doc
            Host elasticsearch.efk.svc.cluster.local
            Port 9200
            tls.verify Off
            Logstash_Format On
            Logstash_Prefix nginx
            Retry_Limit False
            Suppress_Type_Name On

        [OUTPUT]
            Name es
            Match car.*
            Host elasticsearch.efk.svc.cluster.local
            Port 9200
            Index fluent-bit
            Type _doc
            Logstash_Format On
            Logstash_Prefix logstash
            Retry_Limit False
            Suppress_Type_Name On

    customParsers: |
        [PARSER]
            Name nginx_parser
            Format regex
            Regex ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<time_local>[^\]]*)\] "(?<request>[^"]*)" (?<status>[^ ]*) (?<body_bytes_sent>[^ ]*) "(?<http_referer>[^"]*)" "(?<http_user_agent>[^"]*)"
            Time_Key time_local
            Time_Format %d/%b/%Y:%H:%M:%S %z
    #   [PARSER]
    #       Name json_parser
    #       Format json
    #       Time_Key time
    #       Time_Format %Y-%m-%dT%H:%M:%S.%NZ

    #   [PARSER]
    #       Name regex_parser
    #       Format regex
    #       Regex /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
    #       Time_Format %Y-%m-%dT%H:%M:%S.%N%:z
