apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: car-app
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus
spec:
  selector:
    matchLabels:
      argocd.argoproj.io/instance: car-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - car-app
