apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: car-app
  namespace: monitoring
  labels:
    app: car-app
spec:
  selector:
    matchLabels:
      app: car-app-pod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - car-app
