crds:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: oron-carapp.ddns.net
      paths:
        - path: /
          pathType: Prefix

grafana:
  enabled: true
  persistence:
    enabled: true
    type: sts
    storageClassName: "gp2"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
