apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
spec:
  acme:
    server: {{ .Values.clusterissuer.server }}
    email: {{ .Values.clusterissuer.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.privateKeySecretRef.name }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterissuer.ingressClass.name }}