{{- define "mongoPartUri" -}}
  {{- $releaseName := .Release.Name -}}
  {{- $namespace := .Release.Namespace -}}
  {{- $nameOverride := default "mongodb" .Values.mongodb.fullnameOverride -}}
  {{- $replicaCount := .Values.mongodb.replicaCount | int -}}
  {{- range $i := until $replicaCount -}}
    {{- printf "%s-%s-%d.%s-%s-headless.%s.svc.cluster.local:27017" $releaseName $nameOverride $i $releaseName $nameOverride $namespace -}}
    {{- if ne (add1 $i) $replicaCount }},{{ end -}}
  {{- end -}}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  LOG_LEVEL: "info"
  PERSISTENCE: "true"
  MONGODB_PART_URI: {{ include "mongoPartUri" . }}