apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: MONGODB_PART_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: MONGODB_PART_URI
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: LOG_LEVEL
            - name: PERSISTENCE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: PERSISTENCE
            - name: ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: ROOT_USER
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: ROOT_PASSWORD
            - name: MONGODB_URI
              value: mongodb://$(ROOT_USER):$(ROOT_PASSWORD)@$(MONGODB_PART_URI)
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}