apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: car-app-mongodb-secret
  namespace: default
spec:
  encryptedData:
    ROOT_PASSWORD: AgCQbnregS+xKpp5ivAoGLp07Ob9/8K1rVIq+LNa/XN00yqBr4HhN+sozSDPwg4iH3zmEbo5ZEOob29upBmee/GtoK45JPOxKn3Yp4uleqJHh+u8myHyy2hJg4wFIkk+yLhToZAXmNMJ9lq0YXIbGpZyMKrWLxX7O+P2SUeTpp6EEE23gyvIm3hRE0ZoIQwf8Iu+FRBJVsA3U0jM3omojsBPqUjPGgY7UUom80MWCvcGRDNHXqSlB6c58TUW6LGlTC71bFJOreVvC0Z7yC6Y+vHXu0b1OiO1rAYQc1//xoG5HUeXCW9oYNwaMzk9RBQLJxyZwsnp3D8RBozY2NpXY0ihAV4mOpcQDgUAWNhjtJ9FAyGZuVqjpHTfugkCFpZhW60yB5Cf1IEJhGjkXXXZ5SGHZeRQdlIfjL6FN7vXWB5zGu9bFTTu1EWfusv0n0ltf8m4LxGDgJRKZQ6F8txd3Q9HGhoMeDpERykMXtDW+A316CVBh2CMTpoTesOG9DUtWReHDR/083REXn+efoU0oFApDIJUVqpx9jto53Mw2CspF/dMkbyGzkZ12RhgMlRpUemlK3jClbpBUFHfnFKg/N5vLDF89jkYnhN8CGqxC2FkArufjxrHHcDTNhpYqguZBIRaNnEGdSg2Q8doH8IcM7sbA9WOhkJVa9YJ+xU6/iSEJ9UsWNsR2rCDZtQV6t4acYbgj69Z
    ROOT_USER: AgCCF9eNfsOlqm/Zp7v60KPxhjVM4Qsd2OKhfipnLzskulqckkZsyru92/h3WHPwj6lp2zr5S6FepB/6aKbILpXjS1J3HjosY+7fwf7Sc7N9uCLHd5oCPVihlBOYgpDjvDaPRk1Du3kMUMHnH1klOGgqnAwBbwz7Dncz6cIqLpVUuc1n92qPxjzmdg1NRh2XN9fjYx8unJ92SmQwZXvgVTW9kIUxnGpvNeMWgspv6sz1kv8bqaNKFHqWXPgfNPOXy+zStBBOFQDdxdM5Zeorx3Ykn98H/n3g07AF0qi7TE0v6+Swr06vEiNF3U8D5oRwZlgKOWhMZiMmEXICno914JiJzGgAQjl2Sg77/ijekQlekNuhFMdD+rXPyp7gxBD2MWiQLK7gU3M3R+WCZavgChgsZI1Un3EOPXQybhDFVjUbRig2+6jUtpHnjGFc5JmzbaOCNwM2+Pkb0U/UEzjTw6VYzEzucSF3CqPhYmmSt7SCyZVEJrS0X1QMIBPov0vaSzsFcnRI1xReLOf1OrBmZmDLE6EGgxulE3gefZHVZ/vAc3SZshgidarYXC1FjlUy/N/2VdN6JBzW8qkbP89y8nM+etMW40u/29ytBg51A1gIy4/P6QvnY4R+4jdefgRzvBTAZY65CCZEBUfK5ub+ZgUTtC8OA6+K0kqQzhp3w2+lW40k6Lz12+5aLf3INJCt0MbX0Q6w
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: car-app-mongodb-secret
      namespace: default

