{{- define "mongo" }}
  {{- $mongoURI := printf "mongodb://%s:%s@" .Values.mongodb.auth.rootUser .Values.mongodb.auth.rootPassword -}}
  {{- $hosts := "" -}}
  {{- range $i := until (int $.Values.mongodb.replicaCount) -}}
    {{- $currHost := printf "%s-%s-%d" $.Release.Name $.Values.mongodb.nameOverride $i -}}
    {{- $currHost = printf "%s.%s-%s.%s.svc.cluster.local" $currHost $.Release.Name $.Values.mongodb.service.name $.Release.Namespace -}}
    {{- if $hosts -}}
      {{- $hosts = printf "%s,%s" $hosts $currHost -}}
    {{- else -}}
      {{- $hosts = $currHost -}}
    {{- end -}}
  {{- end -}}
  {{- $mongoURI = printf "%s%s:27017" $mongoURI $hosts -}}
  {{ print $mongoURI | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  MONGODB_URI: {{ include "mongo" . }}