apiVersion: v2
name: demo-crm
description: A Helm chart for the Demo CRM application with MongoDB, Ingress, and Cert-Manager
type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
  - name: mongodb
    version: 15.3.0
    repository: "https://charts.bitnami.com/bitnami"
  # - name: ingress-nginx
  #   version: 4.10.1
  #   repository: "https://kubernetes.github.io/ingress-nginx"
  # - name: cert-manager
  #   version: v1.6.1
  #   repository: "https://charts.jetstack.io"
