deployment:
  name: car-app-deployment
  namespace: car-app
  appName: car-app-pod
  containerName: car-app-container
  env:
    - name: MONGODB_URI
      valueFrom:
        secretKeyRef:
          name: car-app-secret
          key: MONGODB_URI

image:
  name: 644435390668.dkr.ecr.ap-south-1.amazonaws.com/oron-portfolio-app
  tag: 1.0.0

configmap:
  name: car-app-conf

service:
  name: car-app-svc
  namespace: car-app
  type: ClusterIP
  port: 80
  targetPort: 5001

ingress:
  name: car-app-ingress
  namespace: car-app
  host: a3a401783adb741eb9471a383a003c74-1442015799.ap-south-1.elb.amazonaws.com
  tlsSecret: a3a401783adb741eb9471a383a003c74-1442015799.ap-south-1.elb.amazonaws.com-tls

clusterissuer:
  name: letsencrypt-prod
  email: oarish96@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretRef:
    name: car-app.ddns.net-tls
  ingressClass:
    name: nginx

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

mongodb:
  architecture: replicaset
  replicaCount: 3
  arbiter:
    enabled: false
  persistence:
    enabled: true
    size: "8Gi"
    storageClass: ""
    accessModes:
      - ReadWriteOnce
  auth:
    enabled: true
    rootPassword: "root"
    rootUser: "root"
  nameOverride: mongodb
  service:
    name: mongodb-headless
  resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "250Mi"
  readinessProbe:
    enabled: false
  livenessProbe:
    enabled: false

secret:
  name: "car-app-secret"
